[package]
name = "danieluntask/signal"
description = "Simple and usefully signal module."
license = "MIT"
version = "0.1.5"
authors = ["Gamer32yttea"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"